### PR TITLE
Add arm64 builds for Docker container

### PR DESCRIPTION
**Pull request by arbourd**
Builds both amd64 and arm64 containers on release.

### CODE REVIEW

**Comment by arbourd** [comment]
Here's the build running on my fork: https://github.com/arbourd/xk6-client-tracing/actions/runs/8469718477

I produced both `amd64` and `arm64` images according to the manifest 

```json
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.oci.image.index.v1+json",
   "manifests": [
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 863,
         "digest": "sha256:92397e2ab66fa0b00675a5e47d34a7c6a90348e1240fe7b7c1ed3d9eb6c5b711",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 863,
         "digest": "sha256:ae07e61de43010ddd8b6b426cf69136c4bcc191e09046a6dcf8df2bcc5a4d40c",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 566,
         "digest": "sha256:b55e8d3a6d08e26e83344fee38db6e7f64ce5eb45c04f30424abc8a0e288a517",
         "platform": {
            "architecture": "unknown",
            "os": "unknown"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 566,
         "digest": "sha256:8d24765285c8cd9409a355507cb238cdb5d2115da1864ab81ff1881da2a09a5e",
         "platform": {
            "architecture": "unknown",
            "os": "unknown"
         }
      }
   ]
}
```

Pulling the image onto my M2 Mac I'm able to see that it correctly pulls the `arm64` variant, compared with the Grafana `amd64`-only image.

Screenshot 2024-03-28 at 12 22 42 PM
Screenshot 2024-03-28 at 12 22 37 PM

**Comment by zalegrala** [comment]
Thank you for the PR.  Do we know what the two `unknown` sections are in the manifest you posted?

**Comment by arbourd** [comment]
I believe that's a build attestation: https://docs.docker.com/build/attestations/

We could disable them by adding `provenance: false`.

**Review by zalegrala — APPROVED** [review]

**Comment by zalegrala** [comment]
Nice, let's see what CI does on merge.  Thanks for the contribution.

**Comment by arbourd** [comment]
Any chance we could get a release featuring this change? 🙏🏻

**Comment by zalegrala** [comment]
https://github.com/grafana/xk6-client-tracing/releases/tag/v0.0.4

Its the first release I've done on this project, so let's see how it goes.

**Pull request merged**
